name: Infra-State-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - infrastructre/state/**

variables:
- group: Contoso-ToDo-VarGroup
- name: isMain
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: artifactName
  value: InfraState
- name: infraScript
  value: infrastructure/state/todoapi-infra-state.ps1
  
stages:

- stage: BuildStage
  displayName: Build Infra State
  jobs:
  - job: BuildInfraState
    steps:
    - task: CopyFiles@2  
      displayName: Copy Artifacts
      inputs:
        Contents: $(infraScript)
        TargetFolder: $(Build.ArtifactStagingDirectory) 

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        ArtifactName: $(artifactName)

- stage: DeployStage
  displayName: Deploy Infra State
  dependsOn: BuildStage    
  # condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: DeployInfraState
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Downloading Artifacts
        inputs:
          artifactName: $(artifactName)
          
      - task: AzureCLI@2
        displayName: Deploying Infra State
        inputs:
            azureSubscription: $(AZURE_SUBSCRIPTION)
            scriptType: pscore
            scriptLocation: scriptPath
            arguments: $(SERVICE_PRINCIPAL_OBJ_ID)
            scriptPath: $(System.ArtifactsDirectory)/$(artifactName)/$(infraScript)
            
    
    
