name: Infra-State-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - infrastructre/state/**

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  artifactName: InfraState
  
stages:

- stage: BuildStage
  displayName: Build Infra State
  jobs:
  - job: BuildInfraState
    steps:
    - task: CopyFiles@2  
      displayName: Copy Artifacts
      inputs:
        Contents: infrastructure/state/*.ps1
        TargetFolder: $(Build.ArtifactStagingDirectory) 

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        ArtifactName: $(artifactName)

- stage: DeployStage
  displayName: Deploy Infra State
  dependsOn: BuildStage    
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: DeployInfraState
    steps:
    - download: current
      displayName: Download Artifacts
      artifact: $(artifactName)
