name: Infra-State-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - infrastructre/state/**

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  artifactName: InfraState
  
stages:

- stage: BuildStage
  displayName: Build Infra State
  jobs:
  - job: BuildInfraState
    steps:
    - task: CopyFiles@2  
      displayName: Copy Artifacts
      inputs:
        Contents: infrastructure/state/*.ps1
        TargetFolder: $(Build.ArtifactStagingDirectory) 

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        ArtifactName: $(artifactName)

- stage: DeployStage
  displayName: Deploy Infra State
  dependsOn: BuildStage    
  # condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: DeployInfraState
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Downloading Artifacts
        inputs:
          artifactName: $(artifactName)
          
      - task: AzureCLI@2
        displayName: Deploying Infra State
        inputs:
            azureSubscription: ContosoAzureConnection
            scriptType: pscore
            scriptLocation: scriptPath
            scriptPath: $(System.ArtifactsDirectory)/infrastructure/state/todoapi-infra-state.ps1
            
    
    
