// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Contoso.Api.Models
{
    /// <summary> The ToDoItem. </summary>
    public partial class ToDoItem
    {
        /// <summary> Initializes a new instance of ToDoItem. </summary>
        public ToDoItem()
        {
        }

        /// <summary> Initializes a new instance of ToDoItem. </summary>
        /// <param name="id"> . </param>
        /// <param name="text"> . </param>
        /// <param name="isCompleted"> . </param>
        /// <param name="created"> . </param>
        /// <param name="completed"> . </param>
        /// <param name="user"> . </param>
        internal ToDoItem(int? id, string text, bool? isCompleted, DateTimeOffset? created, DateTimeOffset? completed, string user)
        {
            Id = id;
            Text = text;
            IsCompleted = isCompleted;
            Created = created;
            Completed = completed;
            User = user;
        }

        public int? Id { get; set; }
        public string Text { get; set; }
        public bool? IsCompleted { get; set; }
        public DateTimeOffset? Created { get; set; }
        public DateTimeOffset? Completed { get; set; }
        public string User { get; set; }
    }
}
